import type { P5SketchLabels } from './p5-node-options';

export const DEFAULT_P5_SKETCH_LABELS = {
  title: 'p5.js sketch',
  edit: 'Edit',
  source: 'Source',
  preview: 'Preview',
  run: 'Run',
  stop: 'Stop',
  restart: 'Restart',
  apply: 'Apply',
  copy: 'Copy',
  resetOriginal: 'Reset to original',
  sourceInput: 'p5.js source',
  copied: 'Copied',
  running: 'Running',
  stopped: 'Stopped',
  error: 'Error',
  resizeLeft: 'Resize from left',
  resizeRight: 'Resize from right',
  capabilities: 'Inputs and devices',
  capabilitiesDescription: 'Only selected capabilities are available to this sketch.',
  suggestedByCode: 'Used in code',
  unsupportedCapability: 'Unavailable here',
  capabilityLabels: {
    camera: 'Camera',
    microphone: 'Microphone',
    motion: 'Motion',
    midi: 'MIDI',
    gamepad: 'Gamepad',
    serial: 'Serial',
    location: 'Location',
    bluetooth: 'Bluetooth',
  },
} satisfies P5SketchLabels;

export const KOREAN_P5_SKETCH_LABELS = {
  title: 'p5.js 스케치',
  edit: '편집',
  source: '소스',
  preview: '미리보기',
  run: '실행',
  stop: '중지',
  restart: '다시 실행',
  apply: '적용',
  copy: '복사',
  resetOriginal: '원본으로 재설정',
  sourceInput: 'p5.js 소스',
  copied: '복사됨',
  running: '실행 중',
  stopped: '중지됨',
  error: '오류',
  resizeLeft: '왼쪽에서 크기 조절',
  resizeRight: '오른쪽에서 크기 조절',
  capabilities: '입력 및 기기',
  capabilitiesDescription: '선택한 기능만 이 스케치에서 사용할 수 있습니다.',
  suggestedByCode: '코드에서 사용 중',
  unsupportedCapability: '현재 환경에서 미지원',
  capabilityLabels: {
    camera: '카메라',
    microphone: '마이크',
    motion: '모션 센서',
    midi: 'MIDI',
    gamepad: '게임패드',
    serial: '시리얼',
    location: '위치 정보',
    bluetooth: 'Bluetooth',
  },
} satisfies P5SketchLabels;
