import { isManagedCdnAssetUrl, toCdnUrl } from './file-url';

export type ManagedImageFit = 'fit' | 'fill';

export interface ManagedImagePreset {
  width: number;
  height?: number;
  fit?: ManagedImageFit;
  quality?: number;
}

export const MANAGED_IMAGE_DEFAULT_QUALITY = 80;

/**
 * Canonical width buckets for managed image delivery.
 *
 * We intentionally round requests up to the next bucket so different callers
 * converge on the same CDN/imgproxy cache keys instead of generating
 * near-duplicate widths such as 347, 360, and 384.
 */
const MANAGED_IMAGE_WIDTH_BUCKETS = [
  32, 48, 64, 96, 128, 160, 192, 256, 320, 480, 640, 768, 960, 1280, 1600, 2048, 2560, 3200, 4096,
] as const;

/**
 * Managed image serving presets.
 *
 * This object is the single source of truth for all raster image transforms
 * generated by the web app. Callers must choose one of these explicit presets
 * instead of passing arbitrary dimensions so we can:
 * - keep CDN/imgproxy cache keys stable
 * - make image intent obvious at the callsite
 * - evolve serving policy in one place without touching every component
 *
 * Notes:
 * - These presets are query variants of one immutable public source (`/asset/...`).
 * - External URLs pass through unchanged.
 * - Vector and animated managed assets (`.svg`, `.gif`) bypass transformation
 *   so we do not rasterize logos/icons or break animation.
 */
export const MANAGED_IMAGE_PRESET = {
  /** Small circular/square avatars rendered around 20-32px. */
  AVATAR_XS: { width: 64, height: 64, fit: 'fill' },
  /** Common list/table avatars rendered around 32-48px. */
  AVATAR_SM: { width: 96, height: 96, fit: 'fill' },
  /** Medium avatars rendered around 48-64px. */
  AVATAR_MD: { width: 160, height: 160, fit: 'fill' },
  /** Large profile avatars rendered around 80px. */
  AVATAR_LG: { width: 256, height: 256, fit: 'fill' },
  /** Small square cover/thumb artwork used in dense rows and tables. */
  COVER_THUMB: { width: 160, height: 160, fit: 'fill' },
  /** Small poster/thumb artwork used in dense event rows and tables. */
  POSTER_THUMB: { width: 160, height: 240, fit: 'fill' },
  /** Square cover artwork used in cards and grids. */
  COVER_CARD: { width: 640, height: 640, fit: 'fill' },
  /** Larger square cover artwork used in detail-page hero sections. */
  COVER_HERO: { width: 1280, height: 1280, fit: 'fill' },
  /** Wide/tall entity header imagery such as artist or label page images. */
  HEADER_IMAGE: { width: 1600 },
  /** Full-width featured/hero imagery such as post featured images. */
  HERO_IMAGE: { width: 1600 },
  /** Rich text/editor body images constrained by content column width. */
  CONTENT_IMAGE: { width: 1600 },
} as const satisfies Record<string, ManagedImagePreset>;

export type ManagedImagePresetName = keyof typeof MANAGED_IMAGE_PRESET;

const MANAGED_IMAGE_BYPASS_EXTENSIONS = new Set(['.svg', '.gif']);

function getManagedImagePreset(preset: ManagedImagePresetName | ManagedImagePreset): ManagedImagePreset {
  if (typeof preset === 'string') {
    return MANAGED_IMAGE_PRESET[preset];
  }

  return preset;
}

function getPathExtension(pathname: string): string {
  const normalizedPath = pathname.toLowerCase();
  const lastDotIndex = normalizedPath.lastIndexOf('.');
  const lastSlashIndex = normalizedPath.lastIndexOf('/');

  if (lastDotIndex === -1 || lastDotIndex < lastSlashIndex) {
    return '';
  }

  return normalizedPath.slice(lastDotIndex);
}

function shouldBypassManagedImageTransform(url: URL): boolean {
  return MANAGED_IMAGE_BYPASS_EXTENSIONS.has(getPathExtension(url.pathname));
}

/**
 * Round an arbitrary image width up to the next canonical managed-image bucket.
 */
export function resolveManagedImageBucketWidth(width: number): number {
  const targetWidth = Math.max(1, Math.round(width));

  for (const bucketWidth of MANAGED_IMAGE_WIDTH_BUCKETS) {
    if (bucketWidth >= targetWidth) {
      return bucketWidth;
    }
  }

  return MANAGED_IMAGE_WIDTH_BUCKETS[MANAGED_IMAGE_WIDTH_BUCKETS.length - 1];
}

/**
 * Build a canonical managed image URL for a preset.
 *
 * Callers must provide a preset constant from `MANAGED_IMAGE_PRESET`. This
 * keeps callsites descriptive and prevents ad-hoc `?w=387` style requests.
 *
 * Behavior:
 * - managed raster media are rewritten to an absolute CDN URL with stable
 *   `w`, optional `h`, optional `fit`, and `q` params
 * - external URLs are returned unchanged
 * - managed `.svg` and `.gif` assets are returned unchanged (except for
 *   relative `/asset/...` normalization to the absolute CDN URL)
 *
 * Important:
 * - Pass raw managed media URLs to `next/image`. The custom Next loader applies
 *   its own bucketed width transform, so helper-generated preset URLs should be
 *   reserved for plain `<img>`, Mantine `Image`, and Mantine `Avatar`.
 */
export function buildManagedImageUrl(
  src: string | null | undefined,
  preset: ManagedImagePresetName | ManagedImagePreset,
): string | null | undefined {
  if (!src) {
    return src ?? null;
  }

  const normalizedSrc = toCdnUrl(src);
  if (!isManagedCdnAssetUrl(normalizedSrc)) {
    return normalizedSrc;
  }

  const url = new URL(normalizedSrc);
  if (shouldBypassManagedImageTransform(url)) {
    return url.toString();
  }

  const resolvedPreset = getManagedImagePreset(preset);
  url.searchParams.set('w', String(resolveManagedImageBucketWidth(resolvedPreset.width)));

  if (resolvedPreset.height && resolvedPreset.height > 0) {
    url.searchParams.set('h', String(resolveManagedImageBucketWidth(resolvedPreset.height)));
  } else {
    url.searchParams.delete('h');
  }

  const fit = resolvedPreset.fit ?? 'fit';
  if (fit === 'fill') {
    url.searchParams.set('fit', fit);
  } else {
    url.searchParams.delete('fit');
  }

  url.searchParams.set('q', String(resolvedPreset.quality ?? MANAGED_IMAGE_DEFAULT_QUALITY));

  return url.toString();
}
