import type { Monaco } from '@monaco-editor/react';

const configuredMonacoInstances = new WeakSet<object>();

const GLSL_KEYWORDS = [
  'attribute',
  'break',
  'buffer',
  'case',
  'centroid',
  'coherent',
  'const',
  'continue',
  'default',
  'discard',
  'do',
  'else',
  'flat',
  'for',
  'highp',
  'if',
  'in',
  'inout',
  'invariant',
  'layout',
  'lowp',
  'mediump',
  'noperspective',
  'out',
  'patch',
  'precision',
  'readonly',
  'restrict',
  'return',
  'sample',
  'shared',
  'smooth',
  'struct',
  'subroutine',
  'switch',
  'uniform',
  'varying',
  'volatile',
  'while',
  'writeonly',
] as const;

const GLSL_TYPES = [
  'bool',
  'bvec2',
  'bvec3',
  'bvec4',
  'double',
  'dmat2',
  'dmat3',
  'dmat4',
  'dvec2',
  'dvec3',
  'dvec4',
  'float',
  'image2D',
  'int',
  'isampler2D',
  'ivec2',
  'ivec3',
  'ivec4',
  'mat2',
  'mat2x2',
  'mat2x3',
  'mat2x4',
  'mat3',
  'mat3x2',
  'mat3x3',
  'mat3x4',
  'mat4',
  'mat4x2',
  'mat4x3',
  'mat4x4',
  'sampler2D',
  'sampler2DArray',
  'sampler2DShadow',
  'sampler3D',
  'samplerCube',
  'samplerCubeShadow',
  'uint',
  'usampler2D',
  'uvec2',
  'uvec3',
  'uvec4',
  'vec2',
  'vec3',
  'vec4',
  'void',
] as const;

/** Registers the local ShaderToy-compatible GLSL grammar once per Monaco instance. */
export function registerGlslLanguage(monaco: Monaco): void {
  if (configuredMonacoInstances.has(monaco)) {
    return;
  }
  configuredMonacoInstances.add(monaco);

  if (!monaco.languages.getLanguages().some(({ id }) => id === 'glsl')) {
    monaco.languages.register({
      id: 'glsl',
      aliases: ['GLSL', 'glsl'],
      extensions: ['.glsl', '.frag', '.vert', '.fs', '.vs'],
      mimetypes: ['text/x-glsl'],
    });
  }

  monaco.languages.setLanguageConfiguration('glsl', {
    comments: { lineComment: '//', blockComment: ['/*', '*/'] },
    brackets: [
      ['{', '}'],
      ['[', ']'],
      ['(', ')'],
    ],
    autoClosingPairs: [
      { open: '{', close: '}' },
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"', notIn: ['string'] },
      { open: "'", close: "'", notIn: ['string', 'comment'] },
    ],
    surroundingPairs: [
      { open: '{', close: '}' },
      { open: '[', close: ']' },
      { open: '(', close: ')' },
      { open: '"', close: '"' },
      { open: "'", close: "'" },
    ],
  });

  monaco.languages.setMonarchTokensProvider('glsl', {
    defaultToken: '',
    tokenPostfix: '.glsl',
    keywords: GLSL_KEYWORDS,
    typeKeywords: GLSL_TYPES,
    operators: [
      '=',
      '>',
      '<',
      '!',
      '~',
      '?',
      ':',
      '==',
      '<=',
      '>=',
      '!=',
      '&&',
      '||',
      '++',
      '--',
      '+',
      '-',
      '*',
      '/',
      '&',
      '|',
      '^',
      '%',
      '<<',
      '>>',
      '+=',
      '-=',
      '*=',
      '/=',
      '&=',
      '|=',
      '^=',
      '%=',
      '<<=',
      '>>=',
    ],
    tokenizer: {
      root: [
        [/^\s*#\s*[a-zA-Z_]+/, 'keyword.directive'],
        [/[a-zA-Z_]\w*/, { cases: { '@typeKeywords': 'type', '@keywords': 'keyword', '@default': 'identifier' } }],
        [/0[xX][0-9a-fA-F]+[uU]?/, 'number.hex'],
        [/(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?[fF]?/, 'number.float'],
        [/\d+(?:[eE][+-]?\d+)[fF]?/, 'number.float'],
        [/\d+[uU]?/, 'number'],
        [/[{}()[\]]/, '@brackets'],
        [/[;,.]/, 'delimiter'],
        [/[<>!=~?:&|+*/^%-]+/, 'operator'],
        [/"([^"\\]|\\.)*$/, 'string.invalid'],
        [/"/, { token: 'string.quote', bracket: '@open', next: '@string' }],
        [/'(?:[^'\\]|\\.)'/, 'string'],
        [/\/\*/, 'comment', '@comment'],
        [/\/\/.*$/, 'comment'],
      ],
      comment: [
        [/[^/*]+/, 'comment'],
        [/\*\//, 'comment', '@pop'],
        [/[/*]/, 'comment'],
      ],
      string: [
        [/[^\\"]+/, 'string'],
        [/\\./, 'string.escape'],
        [/"/, { token: 'string.quote', bracket: '@close', next: '@pop' }],
      ],
    },
  });
}
